// import 'Metadata type from the next package, to define the shape of the metadata object that will be exported later
import type { Metadata } from "next";
// import Inter font that use in the application
import { Inter } from "next/font/google";
//import the Bootstrap CSS and custom global CSS file
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
//import the BootstrapClient components we created
import BootstrapClient from "@/src/components/BootstrapClient";
// create Inter font instance with subset(latin), will apply to HTML elements as font class
const inter = Inter({ subsets: ["latin"] });
//defines the metadata for HTML document, including the title and description, it is exported to used by Next.js to set the metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// define the 'Rootlayout component, and take 'children' as a prop, which prepresents the React nodes that will be rendered inside this layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return a HTML structure for the application
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
